openapi: "3.0.0"
info:
  title: Audited Labels API
  version: "1.0" 
  description: "This API allows for users to directly edit labels on the interface of the iCatcher+ app."
servers:
  - url: http://localhost:5001
paths:
  /studies:
    get:
      operationId: audits.get_studies
      responses:
        "200":
          description: Success
          content: 
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: 
                      type: string
                    path_to_study: 
                      type: string
      
      summary: Get a list of all registered studies

    post: 
      operationId: audits.post_study
      responses: 
        "200": 
          description: Success
          content: 
            text/plain:
              schema: 
                type: string
        "400":
          description: Invalid input directory
          content:
            text/plain:
              schema:
                type: string

      summary: Register a new study 
        
      parameters:
        - name: path_to_study
          in: query
          required: true
          schema:
            type: string

  "/studies/{study_id}/frames":
    get: 
      operationId: audits.get_frames
      responses: 
        "200": 
          description: Success
          content: 
            application/json:
              schema:
                type: array
                items:
                  type: string
        "400":
          description: Invalid input directory or invalid range
        "404":
          description: Study does not exist

      summary: Get the frames of a study. If start and end are provided, get frames in the range [start, end). If only the start is provided, get the frame with index start. If neither are provided, return all frames.
      
      parameters: 
        - name: study_id
          in: path
          required: true
          schema:
            type: string
        - name: start
          in: query
          required: false
          schema: 
            type: number
        - name: end
          in: query
          required: false
          schema:
            type: number

  "/studies/{study_id}/labels":
    get: 
      operationId: audits.get_labels
      responses: 
        "200": 
          description: Success
          content: 
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    label: 
                      type: string
                    confidence: 
                      type: number
                    edited: 
                      type: string
                    merged:
                      type: string
        "400":
          description: Invalid input directory or invalid range
        "404":
          description: Study does not exist

      summary: Get the labels of a study. If start and end are provided, get labels in the range [start, end). If only the start is provided, get the label with index start. If neither are provided, return all labels.
      
      parameters: 
        - name: study_id
          in: path
          required: true
          schema:
            type: string
        - name: start
          in: query
          required: false
          schema: 
            type: number
        - name: end
          in: query
          required: false
          schema:
            type: number

  "/studies/{study_id}/edit":
    post:
      operationId: audits.post_edit
      responses:
        "200":
          description: Success
          content: 
            text/plain:
              schema:
                type: string
        "400":
          description: Invalid edit request
        "404":
          description: Study does not exist

      summary: Register edits to frame labels. If end is provided, edit frames in the range [start, end). If end is not provided, edited only the frame at index start.

      parameters:
        - name: study_id 
          in: path
          required: true
          schema: 
            type: string
        - name: new_label
          in: query
          required: true
          schema:
            type: string
            enum: 
              - left
              - right
              - away
              - noface
        - name: start_frame
          in: query
          required: true
          schema: 
            type: number
        - name: end_frame
          in: query
          required: false
          schema:
            type: number


        


    


  




