openapi: "3.0.0"
info:
  title: Audited Labels API
  version: "1.0" 
  description: "This API allows for users to directly labels on the interface of the iCatcher+ app."
servers:
  - url: http://localhost:5001
paths:
  /studies:
    get:
      operationId: audits.get_studies
      responses:
        "200":
          description: Success
          content: 
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: 
                      type: string
                    path_to_study: 
                      type: string
      
      summary: Get a list of all registered studies

    post: 
      operationId: audits.post_study
      responses: 
        "200": 
          description: Success
          content: 
            text/plain:
              schema: 
                type: string
        "400":
          description: Invalid input directory
          content:
            text/plain:
              schema:
                type: string

      summary: Register a new study 
        
      parameters:
        - name: path_to_study
          in: query
          required: true
          schema:
            type: string

  "/studies/{study_id}":
    get: 
      operationId: audits.get_study
      responses: 
        "200": 
          description: Success
          content: 
            application/json:
              schema:
                type: object
                properties:
                  labels:
                    type: string
                  frames:
                    type: array
                    items:
                      type: string
        "400":
          description: Invalid input directory
          content:
            text/plain:
              schema:
                type: string
        "404":
          description: Study does not exist
          content:
            text/plain:
              schema:
                type: string

      summary: Get the contents (frames and labels) of a study
      
      parameters: 
        - name: study_id
          in: path
          required: true
          schema:
            type: string

  "/studies/{study_id}/edit":
    post:
      operationId: audits.post_edit
      responses:
        "200":
          description: Success
          content: 
            text/plain:
              schema:
                type: string
        "400":
          description: Invalid edit request 
        "404":
          description: Study does not exist

      summary: Register edits to frame labels in a specific range

      parameters:
        - name: study_id 
          in: path
          required: true
          schema: 
            type: string
        - name: frame_range
          in: query
          required: true
          schema:
            type: array
            items: 
              type: integer
        - name: new_label
          in: query
          required: true
          schema:
            type: string

        


    


  




