name: Test iCatcher+
on: [push]
jobs:
  build-project:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[dev]"

      - name: Run tests
        run: python -m pytest tests

  build-ui:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install JS dependencies
      working-directory: ./src/icatcher/icatcher_app/frontend/
      run: npm ci

    - name: Build web app
      working-directory: ./src/icatcher/icatcher_app/frontend/
      run: npm run build

